services:

  db:
    image: postgres:15
    container_name: data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mulsterdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  
#  mcp-server:
#    image: mcp/memory:latest
#    container_name: mcp
#    ports:
#      - "8001:8001"

  mcp-bridge:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-bridge
    container_name: bridge
    env_file: .ngrok
    working_dir: /bridge
    volumes:
      - mcp_data:/bridge/data
    ports:
      - "8000:8000"
    environment:
      NGROK_AUTH_TOKEN: ${NGROK_AUTH_TOKEN}
      PYTHONUNBUFFERED: 1

#  mcp-bridge:
#    build:
#      context: .
#      dockerfile: dockerfiles/Dockerfile-bridge
#    container_name: old-bridge
#
#    depends_on:
#      - mcp-server
#    environment:
#
#      MCP_URL: http://mcp-memory:8001
#    command: tail -f /dev/null

  ollama:
    image: ollama/ollama:latest
    mem_limit: 15g
    memswap_limit: 20g
    build:
      dockerfile: dockerfiles/Dockerfile-llama
    container_name: llama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  app:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-app
    container_name: auto
    env_file: .env
    working_dir: /app
    depends_on:
      - db
      - ollama
      - mcp-bridge
    environment:
      DB_HOST: data
      DB_USER: admin
      DB_PASSWORD: 1234
      DB_NAME: mulsterdb
      OLLAMA_HOST: http://ollama:11434
      PERPLEXITY_API_KEY: ${PERPLEXITY_API_KEY}
    command: tail -f /dev/null

volumes:
  db_data:
  mcp_data:
  ollama_data:
